# Generated by Django 5.2.16 on 2026-07-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='legaldocument',
            new_name='legal_legal_documen_f7bf8e_idx',
            old_name='legal_legal_documen_4cfd8e_idx',
        ),
        migrations.RenameIndex(
            model_name='legaldocument',
            new_name='legal_legal_updated_80f53f_idx',
            old_name='legal_legal_updated_fed3e5_idx',
        ),
    ]
