import { useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Filter, Plus, Search } from "lucide-react";
import { motion } from "framer-motion";
import { useDeleteDocument, useDocuments, useTemplates } from "../features/legal/hooks";
import { DocumentTable } from "../components/legal/DocumentTable";
import { Button, buttonClassName } from "../components/ui/Button";
import { Input, Select } from "../components/ui/Form";
import { Card, SectionHeader } from "../components/ui/Surface";
import { useToast } from "../components/system/Toast";

export default function DocumentsPage() {
  const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState(params.get("search") ?? "");
  const [status, setStatus] = useState(params.get("status") ?? "all");
  const [type, setType] = useState(params.get("document_type") ?? "");
  const [ordering, setOrdering] = useState("-updated_at");
  const [page, setPage] = useState(Number(params.get("page") ?? 1));
  const query = useMemo(() => ({ search, status: status as "all", document_type: type, ordering, page }), [search, status, type, ordering, page]);
  const documents = useDocuments(query);
  const templates = useTemplates();
  const deleteDocument = useDeleteDocument();
  const { notify } = useToast();

  const sync = (nextPage = page) => {
    const next = new URLSearchParams();
    if (search) next.set("search", search);
    if (status !== "all") next.set("status", status);
    if (type) next.set("document_type", type);
    if (nextPage > 1) next.set("page", String(nextPage));
    setParams(next);
  };

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="grid gap-6">
      <SectionHeader
        eyebrow="Repository"
        title="Legal Documents"
        description="Search, filter, sort, and manage every document generated by the platform."
        actions={<Link to="/generate" className={buttonClassName()}><Plus size={16} /> Generate document</Link>}
      />

      <Card className="p-4">
        <div className="grid gap-3 lg:grid-cols-[1fr_180px_220px_auto]">
          <div className="relative">
            <Search size={17} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} onBlur={() => sync()} placeholder="Search by title or content" />
          </div>
          <Select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}>
            <option value="all">All statuses</option>
            <option value="draft">Draft</option>
            <option value="generated">Generated</option>
          </Select>
          <Select value={type} onChange={(event) => { setType(event.target.value); setPage(1); }}>
            <option value="">All document types</option>
            {templates.data?.results.map((template) => <option key={template.id} value={template.document_type}>{template.name}</option>)}
          </Select>
          <Button variant="secondary" onClick={() => sync(1)} icon={<Filter size={16} />}>Apply</Button>
        </div>
      </Card>

      <DocumentTable
        documents={documents.data?.results ?? []}
        count={documents.data?.count ?? 0}
        page={page}
        loading={documents.isLoading}
        onPageChange={(next) => { setPage(next); sync(next); }}
        onSort={setOrdering}
        onDelete={(id) => deleteDocument.mutate(id, { onSuccess: () => notify({ title: "Document deleted", tone: "success" }) })}
      />
    </motion.div>
  );
}
